language: python
python:
  - "3.6"

env:
  - CODACY_PROJECT_TOKEN=877044b500ac460581689f427f67c449

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=apex
  - python-codacy-coverage -r coverage.xml